required = [
    "github.com/coreos/license-bill-of-materials"
]

[prune]
  non-go = true
  go-tests = true
  unused-packages = true

[[constraint]]
name = "github.com/coreos/etcd"
revision = "d267ca9c184e953554257d0acdd1dc9c47d38229"
[[constraint]]
name = "github.com/ghodss/yaml"
revision = "0ca9ea5df5451ffdf184b4428c902747c2c11cd7"
[[constraint]]
name = "github.com/golang/glog"
revision = "23def4e6c14b4da8ac2ed8007337bc5eb5007998"
[[constraint]]
name = "github.com/pborman/uuid"
revision = "ca53cad383cad2479bbba7f7a1a05797ec1386e4"
[[constraint]]
name = "github.com/spf13/cobra"
revision = "4cdb38c072b86bf795d2c81de50784d9fdd6eb77"
[[constraint]]
name = "golang.org/x/crypto"
revision = "0fe963104e9d1877082f8fb38f816fcd97eb1d10"
[[constraint]]
name = "google.golang.org/grpc"
revision = "777daa17ff9b5daef1cfdf915088a2ada3332bf0"
[[constraint]]
name = "k8s.io/api"
version = "kubernetes-1.9.3"
[[constraint]]
name = "k8s.io/apiextensions-apiserver"
version = "kubernetes-1.9.3"
[[constraint]]
name = "k8s.io/apimachinery"
version = "kubernetes-1.9.3"
[[constraint]]
name = "k8s.io/client-go"
version = "kubernetes-1.9.3"
[[constraint]]
name = "k8s.io/kubernetes"
version = "v1.9.3"

[[override]]
name = "cloud.google.com/go"
revision = "3b1ae45394a234c385be014e9a488f2bb6eef821"
[[override]]
name = "github.com/aws/aws-sdk-go"
version = "v1.12.77"
[[override]]
name = "github.com/Azure/go-ansiterm"
revision = "d6e3b3328b783f23731bc4d058875b0371ff8109"
[[override]]
name = "github.com/Azure/go-autorest"
revision = "58f6f26e200fa5dfb40c9cd1c83f3e2c860d779d"
[[override]]
name = "github.com/beorn7/perks"
revision = "3ac7bf7a47d159a033b107610db8a1b6575507a4"
[[override]]
name = "github.com/coreos/license-bill-of-materials"
revision = "6e6186fc66ac0440c6d2302fbee89ede62c97831"
[[override]]
name = "github.com/davecgh/go-spew"
revision = "5215b55f46b2b919f50a1df0eaa5886afe4e3b3d"
[[override]]
name = "github.com/dgrijalva/jwt-go"
revision = "01aeca54ebda6e0fbfafd0a524d234159c05ec20"
[[override]]
name = "github.com/docker/distribution"
revision = "cd27f179f2c10c5d300e6d09025b538c475b0d51"
[[override]]
name = "github.com/docker/docker"
version = "v1.13.1"
[[override]]
name = "github.com/docker/go-connections"
revision = "f549a9393d05688dff0992ef3efd8bbe6c628aeb"
[[override]]
name = "github.com/docker/go-units"
revision = "e30f1e79f3cd72542f2026ceec18d3bd67ab859c"
[[override]]
name = "github.com/docker/spdystream"
revision = "bc6354cbbc295e925e4c611ffe90c1f287ee54db"
[[override]]
name = "github.com/emicklei/go-restful"
revision = "ff4f55a206334ef123e4f79bbf348980da81ca46"
[[override]]
name = "github.com/evanphx/json-patch"
revision = "ba18e35c5c1b36ef6334cad706eb681153d2d379"
[[override]]
name = "github.com/exponent-io/jsonpath"
revision = "d6023ce2651d8eafb5c75bb0c7167536102ec9f5"
[[override]]
name = "github.com/fatih/camelcase"
revision = "f6a740d52f961c60348ebb109adde9f4635d7540"
[[override]]
name = "github.com/go-ini/ini"
version = "v1.32.0"
[[override]]
name = "github.com/go-openapi/jsonpointer"
revision = "46af16f9f7b149af66e5d1bd010e3574dc06de98"
[[override]]
name = "github.com/go-openapi/jsonreference"
revision = "13c6e3589ad90f49bd3e3bbe2c2cb3d7a4142272"
[[override]]
name = "github.com/go-openapi/spec"
revision = "6aced65f8501fe1217321abf0749d354824ba2ff"
[[override]]
name = "github.com/go-openapi/swag"
revision = "1d0bd113de87027671077d3c71eb3ac5d7dbba72"
[[override]]
name = "github.com/gogo/protobuf"
revision = "909568be09de550ed094403c2bf8a261b5bb730a"
[[override]]
name = "github.com/golang/groupcache"
revision = "02826c3e79038b59d737d3b1c0a1d937f71a4433"
[[override]]
name = "github.com/golang/protobuf"
revision = "4bd1920723d7b7c925de087aa32e2187708897f7"
[[override]]
name = "github.com/googleapis/gnostic"
version = "v0.1.0"
[[override]]
name = "github.com/google/btree"
revision = "e89373fe6b4a7413d7acd6da1725b83ef713e6e4"
[[override]]
name = "github.com/google/gofuzz"
revision = "44d81051d367757e1c7c6a5a86423ece9afcf63c"
[[override]]
name = "github.com/gophercloud/gophercloud"
revision = "cf2bbaa52ab69d063466a3c46a5918d05d752625"
[[override]]
name = "github.com/gregjones/httpcache"
revision = "2bcd89a1743fd4b373f7370ce8ddc14dfbd18229"
[[override]]
name = "github.com/grpc-ecosystem/go-grpc-prometheus"
revision = "6b7015e65d366bf3f19b2b2a000a831940f0f7e0"
[[override]]
name = "github.com/grpc-ecosystem/grpc-gateway"
revision = "84398b94e188ee336f307779b57b3aa91af7063c"
[[override]]
name = "github.com/hashicorp/golang-lru"
revision = "a0d98a5f288019575c6d1f4bb1573fef2d1fcdc4"
[[override]]
name = "github.com/howeyc/gopass"
revision = "bf9dde6d0d2c004a008c27aaee91170c786f6db8"
[[override]]
name = "github.com/imdario/mergo"
revision = "6633656539c1639d9d78127b7d47c622b5d7b6dc"
[[override]]
name = "github.com/inconshreveable/mousetrap"
revision = "76626ae9c91c4f2a10f34cad8ce83ea42c93bb75"
[[override]]
name = "github.com/jmespath/go-jmespath"
revision = "0b12d6b5"
[[override]]
name = "github.com/json-iterator/go"
version = "1.0.5"
[[override]]
name = "github.com/juju/ratelimit"
revision = "5b9ff866471762aa2ab2dced63c9fb6f53921342"
[[override]]
name = "github.com/mailru/easyjson"
revision = "d5b7844b561a7bc640052f1b935f7b800330d7e0"
[[override]]
name = "github.com/MakeNowJust/heredoc"
revision = "e9091a26100e9cfb2b6a8f470085bfa541931a91"
[[override]]
name = "github.com/matttproud/golang_protobuf_extensions"
revision = "fc2b8d3a73c4867e51861bbdd5ae3c1f0869dd6a"
[[override]]
name = "github.com/mitchellh/go-wordwrap"
revision = "ad45545899c7b13c020ea92b2072220eefad42b8"
[[override]]
name = "github.com/petar/GoLLRB"
revision = "53be0d36a84c2a886ca057d34b6aa4468df9ccb4"
[[override]]
name = "github.com/peterbourgon/diskv"
version = "v2.0.1"
[[override]]
name = "github.com/prometheus/client_golang"
revision = "c5b7fccd204277076155f10851dad72b76a49317"
[[override]]
name = "github.com/prometheus/client_model"
revision = "fa8ad6fec33561be4280a8f0514318c79d7f6cb6"
[[override]]
name = "github.com/prometheus/common"
revision = "13ba4ddd0caa9c28ca7b7bffe1dfa9ed8d5ef207"
[[override]]
name = "github.com/prometheus/procfs"
revision = "65c1f6f8f0fc1e2185eb9863a3bc751496404259"
[[override]]
name = "github.com/PuerkitoBio/purell"
revision = "8a290539e2e8629dbc4e6bad948158f790ec31f4"
[[override]]
name = "github.com/PuerkitoBio/urlesc"
revision = "5bd2802263f21d8788851d5305584c82a5c75d7e"
[[override]]
name = "github.com/russross/blackfriday"
version = "v2.0.0"
[[override]]
name = "github.com/shurcooL/sanitized_anchor_name"
revision = "86672fcb3f950f35f2e675df2240550f2a50762f"
[[override]]
name = "github.com/Sirupsen/logrus"
version = "v1.0.4"
[[override]]
name = "github.com/spf13/pflag"
revision = "e57e3eeb33f795204c1ca35f56c44f83227c6e66"
[[override]]
name = "golang.org/x/net"
revision = "e90d6d0afc4c315a0d87a568ae68577cc15149a0"
[[override]]
name = "golang.org/x/oauth2"
revision = "a6bd8cefa1811bd24b86f8902872e4e8225f74c4"
[[override]]
name = "golang.org/x/sys"
revision = "8f0908ab3b2457e2e15403d3697c9ef5cb4b57a9"
[[override]]
name = "golang.org/x/text"
revision = "2910a502d2bf9e43193af9d68ca516529614eed3"
[[override]]
name = "google.golang.org/appengine"
revision = "12d5545dc1cfa6047a286d5e853841b6471f4c19"
[[override]]
name = "gopkg.in/gcfg.v1"
version = "v1.2.1"
[[override]]
name = "gopkg.in/inf.v0"
revision = "3887ee99ecf07df5b447e9b00d9c0b2adaa9f3e4"
[[override]]
name = "gopkg.in/warnings.v0"
version = "v0.1.2"
[[override]]
name = "gopkg.in/yaml.v2"
revision = "53feefa2559fb8dfa8d81baad31be332c97d6c77"
[[override]]
name = "k8s.io/apiserver"
version = "kubernetes-1.9.3"
[[override]]
name = "k8s.io/kube-openapi"
revision = "275e2ce91dec4c05a4094a7b1daee5560b555ac9"
[[override]]
name = "k8s.io/utils"
revision = "258e2a2fa64568210fbd6267cf1d8fd87c3cb86e"
[[override]]
name = "vbom.ml/util"
revision = "db5cfe13f5cc80a4990d98e2e1b0707a4d1a5394"
