kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1alpha1
metadata:
  name: system:kube-dns
rules:
  - apiGroups: [""]
    resources: ["*"]
    verbs: ["*"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1alpha1
metadata:
  name: system:kube-dns
subjects:
  - kind: ServiceAccount
    namespace: kube-system
    name: default
roleRef:
  kind: ClusterRole
  name: system:kube-dns
  apiGroup: rbac.authorization.k8s.io
