apiVersion: v1
kind: Pod
metadata:
  name: kube-api-checkpoint
  namespace: kube-system
spec:
  containers:
  - name: checkpoint
    image: quay.io/coreos/pod-checkpointer:f9949bfecdabc573517487d1a5af1e0cd22acf52
    command:
    - /checkpoint
    imagePullPolicy: Always
    volumeMounts:
    - mountPath: /etc/kubernetes
      name: etc-kubernetes
    - mountPath: /srv/kubernetes
      name: srv-kubernetes
  hostNetwork: true
  restartPolicy: Always
  volumes:
  - name: etc-kubernetes
    hostPath:
      path: /etc/kubernetes
  - name: srv-kubernetes
    hostPath:
      path: /srv/kubernetes
