apiVersion: v1
kind: Pod
metadata:
  name: kube-api-checkpoint
  namespace: kube-system
spec:
  containers:
  - name: checkpoint
    image: quay.io/coreos/pod-checkpointer:v0.1.0
    command:
    - /checkpoint
    imagePullPolicy: Always
    volumeMounts:
    - mountPath: /etc/kubernetes
      name: etc-kubernetes
    - mountPath: /srv/kubernetes
      name: srv-kubernetes
    - mountPath: /var/run/secrets/coreos.com/checkpoints
      name: secrets
  hostNetwork: true
  restartPolicy: Always
  volumes:
  - name: secrets
    hostPath:
      path: /var/run/secrets/coreos.com/checkpoints
  - name: etc-kubernetes
    hostPath:
      path: /etc/kubernetes
  - name: srv-kubernetes
    hostPath:
      path: /srv/kubernetes
