apiVersion: v1
kind: Pod
metadata:
  name: kube-api-checkpoint
  namespace: kube-system
spec:
  containers:
  - name: checkpoint
    image: quay.io/coreos/pod-checkpointer:91d5a311eee40d579a8f0549c10eeed57979d6c4
    command:
    - /checkpoint
    imagePullPolicy: Always
    volumeMounts:
    - mountPath: /etc/kubernetes
      name: etc-kubernetes
    - mountPath: /srv/kubernetes
      name: srv-kubernetes
  hostNetwork: true
  restartPolicy: Always
  volumes:
  - name: etc-kubernetes
    hostPath:
      path: /etc/kubernetes
  - name: srv-kubernetes
    hostPath:
      path: /srv/kubernetes
