apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kube-scheduler
  namespace: kube-system
  labels:
    k8s-app: kube-scheduler
    version: v1.4.0-alpha.3_aaron.0
spec:
  template:
    metadata:
      labels:
        k8s-app: kube-scheduler
        version: v1.4.0-alpha.3_aaron.0
    spec:
      containers:
      - name: kube-scheduler
        image: quay.io/peanutbutter/hyperkube:v1.4.0-alpha.3_aaron.0
        command:
        - ./hyperkube
        - scheduler
        - --leader-elect=true
