apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: kubelet
  namespace: kube-system
  labels:
    k8s-app: kubelet
    version: v1.3.4_coreos.0
spec:
  template:
    metadata:
      labels:
        k8s-app: kubelet
        version: v1.3.4_coreos.0
    spec:
      containers:
      - name: kubelet
        image: quay.io/coreos/hyperkube:v1.3.4_coreos.0
        command:
        - /nsenter
        - --target=1
        - --mount
        - --wd=.
        - --
        - ./hyperkube
        - kubelet
        - --api-servers={{ index .APIServers 0 }}
        - --config=/etc/kubernetes/manifests
        - --allow-privileged
        - --hostname-override=$(MY_POD_IP)
        - --cluster-dns=10.3.0.10
        - --cluster-domain=cluster.local
        - --kubeconfig=/etc/kubernetes/kubeconfig
        - --lock-file=/var/run/lock/kubelet.lock
        - --minimum-container-ttl-duration=3m0s
        env:
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: PATH
          value: ./usr/local/sbin:./usr/local/bin:./usr/sbin:./usr/bin:./sbin:./bin
        securityContext:
          privileged: true
        volumeMounts:
        - name: etc-ssl-certs
          mountPath: /etc/ssl/certs
          readOnly: true
      hostNetwork: true
      hostPID: true
      volumes:
      - name: etc-ssl-certs
        hostPath:
          path: /usr/share/ca-certificates
