apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kube-scheduler
  namespace: kube-system
  labels:
    k8s-app: kube-scheduler
    version: v1.3.6_coreos.0
spec:
  selector:
    matchLabels:
      k8s-app: kube-scheduler
  replicas: 2
  template:
    metadata:
      labels:
        k8s-app: kube-scheduler
        version: v1.3.6_coreos.0
    spec:
      containers:
      - name: kube-scheduler
        image: quay.io/coreos/hyperkube:v1.3.6_coreos.0
        command:
        - ./hyperkube
        - scheduler
        - --leader-elect=true
