apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kube-scheduler
  namespace: kube-system
  labels:
    k8s-app: kube-scheduler
    version: v1.2.4_inotify.3
spec:
  template:
    metadata:
      labels:
        k8s-app: kube-scheduler
        version: v1.2.4_inotify.3
    spec:
      containers:
      - name: kube-scheduler
        image: quay.io/peanutbutter/hyperkube:v1.2.4_inotify.3
        command:
        - ./hyperkube
        - scheduler
        - --leader-elect=true
